name: 'Extract specific version from a versions.json file'
description: 'Extract a specific version from a versions.json file used in F3D CI'
inputs:
  file:
    description: 'Local file to recover version information from'
    required: true
  name:
    description: 'Name of the version to extract'
    required: false
    default: ""
  minver_label:
    description: 'Label to control minimum versions'
    required: false
    default: "no-minver"
  special_name:
    description: 'Special name to extract, overriding other inputs'
    required: false
    default: ""

outputs:
  extract:
    value: "${{steps.extract_json.outputs.extract}}"
runs:
  using: "composite"
  steps:

    - name: Check required inputs
      shell: bash
      run: |
        [[ "${{ inputs.file }}" ]] || { echo "file input is empty" ; exit 1; }

    - name: Name to extract is not special name
      if: inputs.special_name == ""
      shell: bash
      run: echo "NAME_TO_EXTRACT=.${{inputs.minver_label == 'minver' && 'min_' || ''}}versions.${{inputs.name}}" >> $GITHUB_ENV

    - name: Name to extract is special name
      if: inputs.special_name != ""
      shell: bash
      run: echo "NAME_TO_EXTRACT=.${{inputs.special_name}}" >> $GITHUB_ENV

    - name: Extract specific json info
      id: extract_json
      shell: bash
      run: echo "extract=$(jq -r '${{env.NAME_TO_EXTRACT}}' < ${{ inputs.file }})" >> $GITHUB_OUTPUT
